# Generated by Django 6.0.5 on 2026-07-24 13:30

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tourism', '0004_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='touristplace',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326),
        ),
    ]
