# Generated by Django 6.0.5 on 2026-05-31 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('SUPER_ADMIN', 'Super Admin'), ('MUNICIPALITY_ADMIN', 'Municipality Admin'), ('DATA_ENTRY_USER', 'Data Entry User'), ('PUBLIC_USER', 'Public User')], default='PUBLIC_USER', max_length=50),
        ),
    ]
